In [ ]:
import numpy as np

In [76]:
import numpy as np
beta = 0.8
threshold = 0.00000000000001

#Yahoo, amazon, msoft


A=[[1, 1, 0],
   [1, 0, 1],
   [0, 1, 0]]

arr= np.array(A, dtype=float)

s=[]
for i in range(0, len(A)):
    s.append(np.sum(arr[:,i]))

# s contains column-wise summations

M=arr

for j in range(0, len(A)):
    M[:,j]=M[:,j]/s[j]


r = (1.0+np.zeros([len(M), 1]))/len(M)

uniD = (1.0-beta)*r
print(uniD)
rprev = r

for i in range(0, 1000):
    r= beta*np.matmul(M, rprev)+uniD
    
    diff = sum(abs(r-rprev))[0]
    #print(i, " ", diff)
    
    if diff<=threshold:
        print("Valur of i=", i)
        break        
    rprev=r
    
print(r)


[[0.06666667]
 [0.06666667]
 [0.06666667]]
Valur of i= 72
[[0.37634409]
 [0.39784946]
 [0.22580645]]


In [ ]:
fig1 =[[1, 0, 1,1,1],
       [1, 0, 0,0,1],
       [0, 1, 1,1,0],
       [0, 0, 1,0,0],
       [0, 0, 1,1,0]]

fig2 =[[0, 0, 1,1,0],
       [1, 0, 0,0,1],
       [0, 1, 1,1,0],
       [0, 0, 1,0,0],
       [0, 0, 1,1,1]]

fig3 =[[1, 0, 0,0,1],
       [0, 0, 1,1,0],
       [0, 1, 1,1,0],
       [0, 0, 1,0,0],
       [0, 0, 1,0,1]]

fig4 =[[0, 0, 1,0,0],
       [1, 0, 1,1,0],
       [0, 1, 1,1,0],
       [0, 0, 1,0,0],
       [0, 1, 0,0,1]]

fig5 =[[0, 0, 0,0,1],
       [0, 1, 1,1,0],
       [0, 1, 0,1,0],
       [0, 0, 1,0,0],
       [0, 0, 1,0,1]]

In [ ]:
beta = 1
threshold = 0.00000000000001
uniD = (1.0-beta)*R

fg = np.array(fig2, dtype=float)
x = np.sum(fg,axis=0)
M = np.divide(fg,x)

R = np.ones_like(M[0])
R = R * 1/len(M)
R = R[:, np.newaxis]
print(R)

[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]


In [ ]:
 for i in range(1000):

  uniD = (1.0-beta)*R
  rprev = R
  R = beta*np.dot(M, rprev)+uniD
  diff = sum(abs(R-rprev))[0]
  if diff<=threshold:
    print("Value of i=", i)
    break  

Value of i= 69


In [ ]:
R

array([[0.11428571],
       [0.22857143],
       [0.34285714],
       [0.08571429],
       [0.22857143]])

In [77]:
def p(beta, fig):
  threshold = 0.00000000000001
  fg = np.array(fig, dtype=float)
  x = np.sum(fg,axis=0)
  M = np.divide(fg,x)

  R = np.ones_like(M[0])
  R = R * 1/len(M)
  R = R[:, np.newaxis]
  uniD = (1.0-beta)*R

  for i in range(1000):
    rprev = R
    R = beta*np.dot(M, rprev)+uniD
    diff = sum(abs(R-rprev))[0]
    if diff<=threshold:
      print("Value of i=", i)
      break

  return R 

In [83]:
print(p(0.6, fig2))
print()
print(p(1, fig2))

Value of i= 32
[[0.147606  ]
 [0.23182331]
 [0.28669998]
 [0.123005  ]
 [0.21086571]]

Value of i= 69
[[0.11428571]
 [0.22857143]
 [0.34285714]
 [0.08571429]
 [0.22857143]]


In [ ]:
figs = [fig1,fig2,fig3,fig4,fig5]

for i in range(5):
  fg = figs[i]
  fg = np.array(fg, dtype=float)
  x = np.sum(fg,axis=0)
  print(x)
  if(0 in x):
    print("fig ",i , " Contains a dead end")
  if(1 in x):
    print("fig ",i, " Contains a spider trap")


[2. 1. 4. 3. 2.]
fig  0  Contains a spider trap
[1. 1. 4. 3. 2.]
fig  1  Contains a spider trap
[1. 1. 4. 2. 2.]
fig  2  Contains a spider trap
[1. 2. 4. 2. 1.]
fig  3  Contains a spider trap
[0. 2. 3. 2. 2.]
fig  4  Contains a dead end
